/* ---------------------------------------------------
 * config.h
 * ---------------------------------------------------
 * GRUPO 1:
 * 	CASTRO, Tomás
 *	FRIGERIO, Dylan
 * 	VALENZUELA, Agustín
 * 	YAGGI, Lucca
 *
 * Profesores:
 * 	MAGLIOLA, Nicolas
 * 	JACOBY, Daniel
 * 	VACATELLO, Pablo
 *
 * fecha: 15/07/2025
 * ---------------------------------------------------*/

#ifndef CONFIG_H
#define CONFIG_H

#define ENEMIES_ROW_MAX						10
#define ENEMIES_COLUMNS_MAX					20
#define PLAYER_LIVES						3
#define INITIAL_SHOOTING_INTERVAL			2000
#define MIN_ENEMY_SHOOTING_INTERVAL			500
#define ENEMY_SHOOTING_INTERVAL_DECREMENT	50
#define MOTHERSHIP_SCORE					100
#define MOTHERSHIP_TRIGGER_SHOTS			5
#define INITIAL_PLAYER_LIVES				3
#define MAX_PLAYER_LIVES					5
#define PLAYER_BULLET_COOLDOWN				250

#ifndef RASPBERRY
#define OFFSET								50
#define SCREEN_H							900
#define ASPECT_RATIO						(16.0f/9.0f)
#define SCREEN_W							(SCREEN_H*ASPECT_RATIO)

#define PLAYER_HEIGHT						0.1f
#define PLAYER_WIDTH						(PLAYER_HEIGHT/ASPECT_RATIO)
#define PLAYER_SPEED						0.00035f
#define PLAYER_BOTTOM_OFFSET				0.9f
#define PLAYER_BULLET_SPEED					0.0015f

#define ENEMY_TOP_OFFSET					0.1f
#define ENEMY_HEIGHT						(0.5f/ENEMIES_ROW_MAX)
#define ENEMY_WIDTH							(0.95f/ENEMIES_COLUMNS_MAX)
#define ENEMY_H_SPACING						(ENEMY_WIDTH)
#define ENEMY_V_SPACING						(ENEMY_HEIGHT*0.5f)
#define ENEMY_INITIAL_SPEED					0.00015f	// #define ENEMY_SPEED		0.00015f
#define ENEMY_SPEED_INCREMENT_PER_LEVEL		0.000025f	// #define ENEMY_SPEED_INCREMENT   0.000005f
#define ENEMY_SPEED_INCREMENT_PER_ROW		(ENEMY_SPEED_INCREMENT_PER_LEVEL/2.0f)
#define ENEMY_SPEED_INCREMENT_PER_ENEMY_KILLED (ENEMY_SPEED_INCREMENT_PER_LEVEL/5.0f)
#define ENEMY_MAX_SPEED						0.01f
#define ENEMY_BULLET_SPEED					0.0005f
#define ENEMY_DESCENT_STEP					((0.5f/SCREEN_H)*OFFSET)

#define BULLET_WIDTH						0.01f
#define BULLET_HEIGHT						0.05f

#define MOTHERSHIP_HEIGHT					0.08f
#define MOTHERSHIP_WIDTH					0.08f
#define MOTHERSHIP_TOP_OFFSET				0.02f
#define MOTHERSHIP_SPEED					0.0003f

#define BARRIER_QUANTITY_MAX				4
#define BARRIER_HEIGHT						(0.5f/BARRIER_QUANTITY_MAX)
#define BARRIER_WIDTH						(0.4f/BARRIER_QUANTITY_MAX)
#define BARRIER_BOTTOM_OFFSET				0.2f
#define BARRIER_SPACING						(BARRIER_WIDTH*2.0f)
#define BARRIER_ROWS						3
#define BARRIER_COLUMNS						5

#else
#define OFFSET 								1
#define ENEMY_DESCENT_STEP					(1.0f/SCREEN_H)
#define SCREEN_W							16
#define SCREEN_H							16
#define BARRIER_ROWS						1
#define BARRIER_COLUMNS						3
#define BARRIER_LIVES						1
#define PLAYER_WIDTH						(4.0f/SCREEN_W)
#define PLAYER_HEIGHT						(2.0f/SCREEN_H)
#define ENEMY_TOP_OFFSET					(2.0f/SCREEN_H)
#define ENEMY_WIDTH							(1.0f/SCREEN_W)
#define ENEMY_HEIGHT						(1.0f/SCREEN_H)
#define ENEMY_H_SPACING						(ENEMY_WIDTH*2.0f)
#define ENEMY_V_SPACING						(ENEMY_HEIGHT*2.0f)
#define PLAYER_SPEED						0.0008f
#define PLAYER_BOTTOM_OFFSET				(1.0f-PLAYER_HEIGHT)
#define ENEMY_INITIAL_SPEED					0.00015f	// #define ENEMY_SPEED		0.00015f
#define ENEMY_SPEED_INCREMENT_PER_LEVEL		0.00015f	// #define ENEMY_SPEED_INCREMENT	0.00003f
#define ENEMY_SPEED_INCREMENT_PER_ROW		(ENEMY_SPEED_INCREMENT_PER_LEVEL/2.0f)
#define ENEMY_SPEED_INCREMENT_PER_ENEMY_KILLED (ENEMY_SPEED_INCREMENT_PER_LEVEL/5.0f)
#define ENEMY_MAX_SPEED						0.0005f
#define BARRIER_WIDTH						(3.0f/SCREEN_W)
#define BARRIER_HEIGHT						(1.0f/SCREEN_H)
#define BARRIER_BOTTOM_OFFSET				(4.0f/SCREEN_H)
#define BARRIER_SPACING						(BARRIER_WIDTH*2.0f)
#define BARRIER_QUANTITY_MAX				2
#define ENEMY_BULLET_SPEED					0.0005f
#define PLAYER_BULLET_SPEED					0.0010f
#define BULLET_WIDTH						(1.0f/SCREEN_W)
#define BULLET_HEIGHT						(1.0f/SCREEN_H)
#define MOTHERSHIP_WIDTH					(4.0f/SCREEN_W)
#define MOTHERSHIP_HEIGHT					(1.0f/SCREEN_H)
#define MOTHERSHIP_TOP_OFFSET				0.0f
#define MOTHERSHIP_SPEED					0.00045f
#endif

#define BLOCK_HEIGHT						(BARRIER_HEIGHT/BARRIER_ROWS)
#define BLOCK_WIDTH							(BARRIER_WIDTH/BARRIER_COLUMNS)

#endif // CONFIG_H